// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOWGk67Va-K6OzrSTvqbg3s0jmLxTKBQ',
    appId: '1:898418353105:web:875c56430c4a1d2a1876f0',
    messagingSenderId: '898418353105',
    projectId: 'chat-app-abdo2',
    authDomain: 'chat-app-abdo2.firebaseapp.com',
    storageBucket: 'chat-app-abdo2.appspot.com',
    measurementId: 'G-CPSR73R222',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHumKuzuigQVsKw237JQOSqmtyDmOxg8',
    appId: '1:898418353105:android:00ae7cdd1ca016741876f0',
    messagingSenderId: '898418353105',
    projectId: 'chat-app-abdo2',
    storageBucket: 'chat-app-abdo2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGsYZ1hJBm9n-CMWuO2MBvIBziZHVCkos',
    appId: '1:898418353105:ios:66954205b2bed3bf1876f0',
    messagingSenderId: '898418353105',
    projectId: 'chat-app-abdo2',
    storageBucket: 'chat-app-abdo2.appspot.com',
    iosBundleId: 'com.example.chatAppAbdo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGsYZ1hJBm9n-CMWuO2MBvIBziZHVCkos',
    appId: '1:898418353105:ios:66954205b2bed3bf1876f0',
    messagingSenderId: '898418353105',
    projectId: 'chat-app-abdo2',
    storageBucket: 'chat-app-abdo2.appspot.com',
    iosBundleId: 'com.example.chatAppAbdo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeOWGk67Va-K6OzrSTvqbg3s0jmLxTKBQ',
    appId: '1:898418353105:web:3173956a49703c561876f0',
    messagingSenderId: '898418353105',
    projectId: 'chat-app-abdo2',
    authDomain: 'chat-app-abdo2.firebaseapp.com',
    storageBucket: 'chat-app-abdo2.appspot.com',
    measurementId: 'G-RJL60E64R5',
  );
}
